#
#

# H_{\omega,k}X_{k}^{\omega}H_{\omega,k}=X_{\omega}^{k}
# X_{l}^{h,\omega}X_{h}X_{l}^{h,\omega}=X_{h}X_{l}^{\omega}
X_{l}^{h,k,m}X_{h}X_{l}^{h,k,m}=X_{l}^{k,m}X_{h}
X_{l}^{h,k}X_{h}X_{l}^{h,k}=X_{l}^{k}X_{h}
# X_{\omega}X_{\omega}=I_{\omega}
X_{l}X_{l,h}=X_{h}